export const TOOGLE_INGREDIENT = "TOOGLE_INGREDIENT";
export const DELETE_INGREDIENT = "DELETE_INGREDIENT";
export const TOOGLE_TAG = "TOOGLE_TAG";
export const TOOGGLE_BLACKLIST = "TOOGGLE_BLACKLIST";
export const RESET_INGREDIENT = "RESET_INGREDIENT";
export const DELETE_TAG = "DELETE_TAG";
